<section>
          
          <article>
            
            <p> Merci.</p>
            <p>  Votre message a bien été envoyé.</p>
            <p>Nous vous répondrons rapidement. </p>
          
            <p> Continuez à explorer nos services ci-dessous ! </p>
          
            <a href="<?= $requestUrl ?>/"> 
              
              <button type="button" class="button">
                <span>Revenir à l'accueil</span>
              </button> 
                
            </a>
              
          </article>
         
</section>