<section id="section1" class="clear">

        <div class="lesblocs">
            
            <article class="bloc">
                <img src="<?= $wwwUrl ?>/images/folder.svg" alt="">
                <h4> Création</h4>
                    <p>
                        Créer un site web, respectant votre image, votre charte graphique et vos exigences requière un spécialiste à votre écoute et 
                        qualifiée dans le domaine de la création de site internet.
                    </p>
                        <br>
                    <button onclick="window.location.href='<?= $requestUrl ?>/devis'" class="savoirplus1" type="button"> En savoir plus </button> 

            </article>

            <article class="bloc">
                <img src="<?= $wwwUrl ?>/images/coding.svg" alt="">
                <h4> Référencement</h4>
                    <p>
                        Le référencement web représente un enjeu capital dans la création de site internet, utilise chaque jour les moteurs de recherche, 
                        pour trouver le site web qui répondra à leur besoin.
                    </p>
                        <br>
                    <button onclick="window.location.href='<?= $requestUrl ?>/devis'" class="savoirplus2" type="button"> En savoir plus </button> 
            </article>

            <article  class="bloc">
                <img src="<?= $wwwUrl ?>/images/notes.svg" alt="">
                <h4> Fonctionnalités</h4>
                    <p>
                        Boostez votre site web en y intégrant des fonctionnalités intéressantes, un site web riche en fonctionnalités et en contenu est un 
                         web attractif et qui vous générera plus de trafic.
                    </p>
                        <br>
                    <button onclick="window.location.href='<?= $requestUrl ?>/devis'" class="savoirplus3" type="button"> En savoir plus </button> 
            </article>

            <article class="bloc">
                <img src="<?= $wwwUrl ?>/images/facebook.svg" alt="facebookImg">
                <h4> Médias Sociaux</h4>
                    <p>
                        Avec les réseaux sociaux, tout devient possible. Notre méthode de travail à la fois simple et compliquée , nous avons un community
                         manager, un expert en place qui gère toutes vos pages.
                    </p>
                        <br>
                    <button onclick="window.location.href='<?= $requestUrl ?>/devis'" class="savoirplus4" type="button"> En savoir plus </button> 
            </article>
        </div>

        </section>

            
                                            <!-- *** Section 2 *** -->
                

        <section class="section2">

            <hr class="stylehr"> 

               <article id="partie1"> 
                   <h3> LA RÉVOLUTIONS DIGITALE QUI N’ARRÊTE PAS DE VOUS IMPRESSIONER </h3>
                        <p>Création Site Web, Référencement Naturel, Médias Sociaux, Rédaction Web, Référencement payant Adwords. </p>

                        <button onclick="window.location.href='<?= $requestUrl ?>/estimerTarif'" class="demandedevis" type="button"> ESTIMER LE TARIF </button>
                        
                </article>
                <br>
                <br>
                <br>

                <div id='img1'>
                   <img class="img1" src="<?= $wwwUrl ?>/images/ir5likvfqc4-william-iven-1920x1275.jpg" alt="">
                </div>

                <article class="aide">

                    <h4> AIDE À LA CRÉATION DE SITE INTERNET </h4>
                    <span> Un accompagnement à l'administration de votre site </span>
                    <p> Notre équipe technique basée en France, vous apporte une aide gratuite et rapide pour les questions approfondies concernant la création de votre site web. </p>
                    <p> Chaque demande est traitée de façon individuelle et personnalisée par message en moins de 48 heures. </p>
                
                </articles>
               
            <hr class="stylehr2">
        </section>

           
                
            

                                            <!-- *** Section 3 *** -->

        <section id="section3">

            <hr class="stylehr">
            
            <article>
                
                <h3>NOTRE ÉQUIPE</h3>

                    <p>
                    Vous ne nous avez peut-être pas encore contacté mais sachez que notre équipe est composée de personnes géniales, avec plusieurs talents.
                    </p>
                    <p>
                    Chacune donne d’elle-même tous les jours pour vous garantir un meilleur service.
                    </p>
                    
            </article>
                    <br>

            <article class="equipe">

                <img class="imgequipe" src="<?= $wwwUrl ?>/images/mohamed.jpeg" alt="">
                <p>Mohamed FAROUQ</p>
                <span>DÉVELOPPEUR FRONT-END</span>

            </article>

            <article class="equipe">

                <img class="imgequipe" src="<?= $wwwUrl ?>/images/amar.jpeg" alt="">
                <p>Amar JAHA </p>
                <span> DÉVELOPPEUR BACK-END</span>

            </article>

            <article class="equipe">

                <img class="imgequipe" src="<?= $wwwUrl ?>/images/venushan.jpg" alt="">
                <p>Venushan PANCHAN</p>
                <span> REFERENCEMENT WEB</span>

            </article>

            <hr class="stylehr2">
            
        </section>