<section>
          <p>
                <?= $name; ?> <br> Nous vous remercions pour votre demande de devis!
          <p>
                Merci pour cette requête et de l'intérêt que vous portez à nos prestations </p>
          <p>
                Votre demande a bien été prise en compte et vous recevrez votre devis par email dans les meilleurs délais.
          </p>
          <p>
                Si vous désirez de plus amples informations, n'hésitez pas à nous contacter par email ou téléphone.
          </p>
          <p>
                Nous serons ravis de vous fournir de plus amples informations et de répondre à toutes vos questions. 
          </p> 
          <p>
                Continuez à explorer nos services ci-dessous!
          </p>
          
          <a href="<?= $requestUrl ?>/"> Revenir à l'accueil</a>
</section>